import React from 'react'
import Layout from './components/Layout'

export default function About() {
  return (
    <Layout>
    <div>
      <h1>About Page</h1>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptate, labore quos? Dolorum delectus aut sed repudiandae explicabo quis ipsum assumenda numquam? Deserunt odit ad optio asperiores aperiam explicabo blanditiis, cumque modi veritatis corrupti inventore ab? Iusto mollitia debitis perferendis enim impedit adipisci culpa molestiae, tenetur et commodi tempore beatae, nostrum qui labore iure hic eos deserunt soluta est obcaecati facere, ab ipsum. Dolores consequuntur repudiandae recusandae modi, dolore blanditiis incidunt odit, autem voluptate totam commodi iusto eius eum nobis ullam nisi et laboriosam veniam molestias dignissimos minima dolor ex atque harum! Sit nobis, sequi itaque blanditiis rerum et quis explicabo. Commodi in necessitatibus aperiam, at eaque, asperiores suscipit laborum illum et placeat quaerat iste maiores expedita quidem odio neque, blanditiis quasi aspernatur exercitationem deserunt nam! Commodi dolor incidunt ipsam dicta deleniti unde fugiat dolorem enim officiis, culpa odio necessitatibus omnis corporis ipsa? Facilis deserunt ratione quidem optio minima at, accusamus itaque, voluptas asperiores sequi praesentium nemo repellat, eligendi sint inventore incidunt tenetur pariatur rem veniam! Odio harum tempora sint veniam consectetur omnis iste obcaecati possimus maxime hic esse, cum, tempore ut excepturi illo, libero dolorum facere consequatur eaque recusandae quibusdam aliquam doloribus eveniet aspernatur. Omnis ut dolores architecto quae quas?</p>
      <p>Temporibus iure, explicabo velit eum neque non, accusamus quisquam odit repudiandae adipisci nostrum praesentium fuga, perspiciatis facere. Illo itaque fugit repudiandae voluptatem error sed ratione ut harum cupiditate consequuntur quisquam atque velit, veritatis sapiente minima in qui dolorem explicabo praesentium deserunt, dolore aliquid quas. Quia dolores eius error architecto, placeat dicta asperiores iusto aspernatur ullam reprehenderit dignissimos odio fugit nihil reiciendis molestias nemo pariatur id ducimus autem, totam cum ut maxime quis aliquid? Perferendis laborum fugiat nam? Veritatis cum, quasi enim adipisci consectetur obcaecati quo, itaque ad molestias saepe neque, debitis corporis blanditiis ipsa iste voluptates asperiores quaerat ea sapiente error expedita nisi eligendi eveniet. Tenetur nesciunt recusandae, nulla fugiat illo id blanditiis magni perspiciatis sunt. Quae reiciendis sunt dignissimos quo? Tenetur libero sapiente saepe obcaecati laborum dolore tempora? Illum aliquam molestias doloremque. Id doloremque distinctio earum illum! Consequatur distinctio blanditiis modi sed? Cum dicta totam tempora, rerum inventore ratione deleniti possimus natus magnam architecto, est perspiciatis, quia quae perferendis autem saepe commodi obcaecati! Excepturi porro molestias omnis! Magnam repellendus quidem velit eligendi, iure minima explicabo cumque odit impedit atque incidunt. Delectus, praesentium quis pariatur atque recusandae alias minus hic autem, sint eius eos tempore ut vitae, reprehenderit dolor voluptatem.</p>
      <p>Odit error corrupti in commodi magni quaerat beatae eum hic, quasi illo sint veniam! Ab non qui odit quas laudantium numquam illo? Tempore nam explicabo facilis numquam. Dolore laboriosam veniam eveniet animi, ab impedit nihil sed tempora esse consectetur ullam atque sapiente placeat. At ex dolore facere quia? Aut praesentium atque, consequatur cum ratione quae officiis iusto omnis impedit laudantium, repellat error dignissimos. Repellat ea voluptates omnis incidunt tenetur illo iusto. Ipsam enim illo nemo voluptatibus, accusantium voluptate quaerat, earum ab culpa itaque nam obcaecati deleniti repellat eius sapiente id accusamus hic fuga sequi a iure. Provident qui, atque natus quae fuga ullam impedit veritatis alias odit dolorem culpa sint at excepturi debitis consectetur molestias, quas explicabo, error suscipit quasi. Velit et facilis, accusantium similique odit ipsum eum recusandae, iusto excepturi, autem ea sequi impedit asperiores at ipsa iste omnis mollitia sint. Delectus, sequi! Blanditiis dignissimos culpa quia fugit reprehenderit ullam consequatur obcaecati tempore. Ipsum deleniti perspiciatis deserunt consequuntur architecto sint expedita ab recusandae possimus tempore error perferendis unde dignissimos nobis, aperiam sed quaerat commodi libero ea consequatur? Quasi, delectus veritatis quos vero ipsam ullam corporis ducimus temporibus, ut officia, voluptas alias perspiciatis ea quibusdam assumenda! Aspernatur perspiciatis adipisci blanditiis.</p>
    </div>
    </Layout>
  )
}
